# Experiment 10

# Create Dataset and Load Dataset

## Name - Arnav Pandey
## PRN - 25070123023
## Batch - ENTC A2

In [ ]:
# Example
import pandas as pd

data = {
    "Roll_No": [67, 41, 7, 10],
    "Gender": ["Female", "Male", "Male", "Female"],
    "Department": ["CSE", "ECE", "CIVIL", "MECH"],
    "CGPA": [7.4, 9.1, 6.2, 10]
}

df = pd.DataFrame(data)

df.to_csv("student.excel", index=False)
df

   Roll_No  Gender Department  CGPA
0       67  Female        CSE   7.4
1       41    Male        ECE   9.1
2        7    Male      CIVIL   6.2
3       10  Female       MECH  10.0

In [ ]:
df.shape

(4, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     4 non-null      int64
 1   Gender      4 non-null      object
 2   Department  4 non-null      object
 3   CGPA        4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.size

16

In [ ]:
# Access informatiom of Column Department
df["Department"]

0      CSE
1      ECE
2    CIVIL
3     MECH
Name: Department, dtype: object

In [ ]:
# Access information of PRN 67
df[df["Roll_No"] == 67]

   Roll_No Department  CGPA Grade
0       67        CSE   7.4     F

In [ ]:
# Find out datatype of each column
a = df.dtypes
a

Roll_No         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
# Perform mean, median, mode operation
a = df["CGPA"].mean()
b = df["CGPA"].median()
c = df["CGPA"].mode()
print(a)
print(b)
print(c)

8.175
8.25
0     6.2
1     7.4
2     9.1
3    10.0
Name: CGPA, dtype: float64

In [ ]:
# Insert a new column grade
df["Grade"] = ["F","A","F","A"]
display(df)

   Roll_No  Gender Department  CGPA Grade
0       67  Female        CSE   7.4     F
1       41    Male        ECE   9.1     A
2        7    Male      CIVIL   6.2     F
3       10  Female       MECH  10.0     A

In [ ]:
# Delete Gender Column
df.drop("Gender", axis=1 , inplace=True)
df

   Roll_No Department  CGPA Grade
0       67        CSE   7.4     F
1       41        ECE   9.1     A
2        7      CIVIL   6.2     F
3       10       MECH  10.0     A

In [ ]:
# CGPA of topper
df["CGPA"].max()

10.0

In [ ]:
# CGPA of 41
display(df[df["Roll_No"] == 41]["CGPA"])

1    9.1
Name: CGPA, dtype: float64

In [ ]:
# Upload the dataset
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.shape

(93, 10)

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0